In [3]:
##NumPy is the base of all other libraries in the PyData Ecosystem such as Pandas and MatPlotLib.

In [5]:
import numpy as np

In [9]:
list1=[1,2,3,4]
arr=np.array(list1)
arr

array([1, 2, 3, 4])

In [10]:
type(arr)

numpy.ndarray

In [22]:
nested_list=[[1,2,3],[4,5,6],[9,9,7]]
np.array(nested_list)

array([[1, 2, 3],
       [4, 5, 6],
       [9, 9, 7]])

In [35]:
np.arange(0,10,3) #Start at 0, to (10-1) in steps of 3

array([0, 3, 6, 9])

In [36]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [37]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [61]:
np.linspace(0,10,15) #give an equally spaced array of 15 qty betweeb 0 and 10

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [60]:
np.linspace(0,10,15,dtype=np.int32)

array([ 0,  0,  1,  2,  2,  3,  4,  5,  5,  6,  7,  7,  8,  9, 10])

In [63]:
np.eye(4) #give an identity array (matrix) 4X4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [104]:
np.random.rand(2) #generates one dim random array

array([0.5705773 , 0.57559734])

In [67]:
#generates random 2 dim. array. Random values will always be between 0 and 1 (here 3 dim arraygenerates random one dim. array )
np.random.rand(3,3) 

array([[0.6738349 , 0.96258734, 0.18630168],
       [0.50020751, 0.72261769, 0.71249839],
       [0.77745663, 0.46323149, 0.0988942 ]])

In [82]:
np.random.randn(1,3) #standard normal dist = (x - mean)/std deviation (here mean is 0 in std deviation)

array([[1.95574245, 0.97118341, 0.05995491]])

In [102]:
np.random.randint(90,100) #generate a random number

91

In [108]:
#vectors
arr=np.arange(25)
ranarr=np.random.randint(0,50,10)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [107]:
arr.shape #this is converting to a vector

(25,)

In [117]:
arr.reshape(5,5) #now this is an array (not a vector, vector is always one dimensional and directionless (can't say row or col))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [119]:
arr.reshape(5,5).shape

(5, 5)

In [122]:
ranarr

array([ 6, 46, 31, 48, 43, 29, 36,  7, 25, 43])

In [123]:
ranarr.max()

48

In [125]:
ranarr.argmax() #index of the max value

3

In [129]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [131]:
np.transpose(arr) #get the transpose

array([[ 0,  5, 10, 15, 20],
       [ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]])

In [139]:
ar1=np.arange(0,10)
ar1[3]

3

In [141]:
ar1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [140]:
ar1[0:5]

array([0, 1, 2, 3, 4])

In [142]:
ar1[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [152]:
print(list(item*2 for item in ar1))

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [156]:
ar2=np.arange(0,11)
ar2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [159]:
ar2[:]=99
ar2

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [161]:
ar2[1:4]=66
ar2

array([99, 66, 66, 66, 99, 99, 99, 99, 99, 99, 99])

In [162]:
ar3=ar2[1:6]
ar3

array([66, 66, 66, 99, 99])

In [171]:
ar3[1:2]=89 
ar3

array([66, 89, 66, 99, 99])

In [172]:
ar2

array([99, 66, 89, 66, 99, 99, 99, 99, 99, 99, 99])

In [174]:
ar3_copy=ar2.copy()
ar3_copy

array([99, 66, 89, 66, 99, 99, 99, 99, 99, 99, 99])

In [178]:
ar3_copy[:]=74
ar3_copy

array([74, 74, 74, 74, 74, 74, 74, 74, 74, 74, 74])

In [179]:
ar2

array([99, 66, 89, 66, 99, 99, 99, 99, 99, 99, 99])

In [197]:
arr_2d=np.array([[5,10,15],[20,25,30],[30,35,40]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [30, 35, 40]])

In [193]:
arr_2d[1]

array([20, 25, 30])

In [194]:
arr_2d[1][1]

25

In [195]:
arr_2d[1,1]

25

In [196]:
arr_2d[1:,1:]

array([[25, 30],
       [35, 40]])

In [202]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [203]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [200]:
bln_Arr=arr>4
arr[bln_Arr]

array([ 5,  6,  7,  8,  9, 10])

In [201]:
arr[arr<6]

array([1, 2, 3, 4, 5])

In [204]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [30, 35, 40]])

In [210]:
arr_2d[arr_2d%2==0]

array([10, 20, 30, 30, 40])

In [222]:
ar1=np.arange(0,10)
ar1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [214]:
ar1+ar1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [217]:
ar1*ar1

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [220]:
1/(ar1[1:]*ar1[1:])

array([1.        , 0.25      , 0.11111111, 0.0625    , 0.04      ,
       0.02777778, 0.02040816, 0.015625  , 0.01234568])

In [223]:
np.sqrt(ar1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [224]:
np.exp(ar1)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [225]:
np.sin(ar1)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [226]:
np.log(ar1)

C:\Users\Siva\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [227]:
np.ceil(24.567)

25.0

In [228]:
np.floor(56.23)

56.0

In [229]:
np.round(34.567)

35.0

In [234]:
arr1=np.asarray(np.arange(2,7))
arr1

array([2, 3, 4, 5, 6])

In [235]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [30, 35, 40]])

In [236]:
arr_2d.flatten()

array([ 5, 10, 15, 20, 25, 30, 30, 35, 40])

In [238]:
fn=lambda a,b: np.arange(1,10) * (a/b)
fn(3,4)

array([0.75, 1.5 , 2.25, 3.  , 3.75, 4.5 , 5.25, 6.  , 6.75])